base_url = "https://keygate.io"
build_search_index = true
compile_sass = true
generate_feed = true

[markdown]
highlight_code = true
highlight_theme = "dracula"

[search]
include_content = true
include_description = false
include_title = true

[extra]
language_code = "en"
